packages: []

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  esbuild: true
  msgpackr-extract: true
  workerd: true
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
